application: protein-interaction
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: protein.app
  
libraries:
- name: jinja2
  version: latest